### ISSUE TITLE
nx format check

### ISSUE THREAD

**Issue by Fallenstedt** [jsonberry/pentacle#37]
Each time I try to commit something, I can pass the commitlint however I fail `nx format:check`. I don't know what this is and I am having trouble finding information about this online. 

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/wn692np/.nvm/versions/node/v10.7.0/bin/node',
1 verbose cli   '/Users/wn692np/.nvm/versions/node/v10.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'format:check' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'preformat:check', 'format:check', 'postformat:check' ]
5 info lifecycle pentacle@0.0.0~preformat:check: pentacle@0.0.0
6 info lifecycle pentacle@0.0.0~format:check: pentacle@0.0.0
7 verbose lifecycle pentacle@0.0.0~format:check: unsafe-perm in lifecycle true
8 verbose lifecycle pentacle@0.0.0~format:check: PATH: /Users/wn692np/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/wn692np/Code/pentacle/node_modules/.bin:/Users/wn692np/Code/pentacle/node_modules/.bin:/Users/wn692np/Code/node_modules/.bin:/Users/wn692np/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/wn692np/.nvm/versions/node/v10.7.0/bin:/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core:/Users/wn692np/.cargo/bin:/Users/wn692np/.nvm/versions/node/v10.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin
9 verbose lifecycle pentacle@0.0.0~format:check: CWD: /Users/wn692np/Code/pentacle
10 silly lifecycle pentacle@0.0.0~format:check: Args: [ '-c', 'nx format:check' ]
11 silly lifecycle pentacle@0.0.0~format:check: Returned: code: 1  signal: null
12 info lifecycle pentacle@0.0.0~format:check: Failed to exec format:check script
13 verbose stack Error: pentacle@0.0.0 format:check: `nx format:check`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/wn692np/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/wn692np/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid pentacle@0.0.0
15 verbose cwd /Users/wn692np/Code/pentacle
16 verbose Darwin 17.7.0
17 verbose argv "/Users/wn692np/.nvm/versions/node/v10.7.0/bin/node" "/Users/wn692np/.nvm/versions/node/v10.7.0/bin/npm" "run" "format:check"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error pentacle@0.0.0 format:check: `nx format:check`
22 error Exit status 1
23 error Failed at the pentacle@0.0.0 format:check script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Is there something obvious I am missing? Does this project need to use a specific version of node or npm?

**Comment by jsonberry** [comment]
🤔 

Here is the husky setup:
```
  "husky": {
    "hooks": {
      "pre-commit": "npm run format:check",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
```

If you `npm i`, you should be up-to-date after that if you haven't installed recently, I'm running node v `10.13.0`, but for no other reason than it's close to the latest LTS version.

You can run `npm run format:check` to see what would be caught

You can run `npm run affected:format` to format all affected files, which should be anything that would need formatting.

Lemme know if you're still having trouble!

**Comment by Fallenstedt** [comment]
Nuking node modules, running `npm run affected:format`, then `npm run format:check` and finally committing made it pass.  🥇
